services:
  tradereg: 
    image: gerogiordano08/trade-registry
    env_file:
      - .env
    secrets:
      - django_secret_key
      - email_host_user
      - email_host_password
      - finnhub_api_key
      - postgres_user
      - postgres_password
    command: gunicorn --config gunicorn_config.py the_trade_registry.wsgi:application 
    expose:
      - "8000"
    volumes:
      - ./staticfiles:/app/staticfiles
      - ./logs/:/usr/src/app/logs/
    restart: always
    depends_on:
      - db
      - redis

  db:
    image: postgres:15-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tr-reg
      - POSTGRES_USER_FILE=/run/secrets/postgres_user
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres_password
    secrets:
      - postgres_user
      - postgres_password

  redis:
    image: redis:alpine

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot
      - ./staticfiles:/app/staticfiles
    depends_on:
      - tradereg

  certbot:
    image: certbot/certbot
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/www:/var/www/certbot:rw
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"

secrets:
  django_secret_key:
    file: ./.secrets/django_secret_key.txt
  email_host_user:
    file: ./.secrets/email_host_user.txt
  email_host_password:
    file: ./.secrets/email_host_password.txt
  finnhub_api_key:
    file: ./.secrets/finnhub_api_key.txt
  postgres_user:
    file: ./.secrets/postgres_user.txt
  postgres_password:
    file: ./.secrets/postgres_password.txt

volumes:
  postgres_data: